// Note: Main layout file for a Next.js application...!

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// Import Mantine UI Integration...!
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';
import { ColorSchemeScript, mantineHtmlProps } from '@mantine/core';

// Import global styles...!
import "./globals.css";

// Note: Importing required components...!
import ReduxProvider from "@/components/redux-provider/redux-provider";
import Navbar from "@/components/navbar/navbar";

// Fonts...!
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode; }>) => {
  return (
    <html
      lang="en"
      {...mantineHtmlProps}
    >
      <head>
        <title> Techinoviq Assessment </title>
        <ColorSchemeScript />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReduxProvider>
          <Navbar />

          {/* Main Application Content...! */}
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;